"""Regenerate the reference with Nmap's own parser and payload selection API.

Usage: python3 tests/nmap_reference.py /path/to/pristine/pinned/nmap-source
Requires a C/C++ build toolchain and make. Builds a temporary copy; does not scan.
The supplied source must be the commit recorded below (e.g. a GitHub tarball).
"""
import collections
import hashlib
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
COMMIT = "24229f2e65aa11ca860b5c4ec6b4757dc2d8afd0"
VERSION = "7.991SVN"
DUMP = r"""
  init_payloads();
  for (unsigned int port = 0; port <= 65535; ++port) {
    for (unsigned int index = 0; index < udp_payload_count(port); ++index) {
      int length = 0;
      const u8 *payload = get_udp_payload(port, &length, index);
      printf("%u\t", port);
      for (int byte = 0; byte < length; ++byte) printf("%02x", payload[byte]);
      printf("\n");
    }
  }
  return 0;
"""


def compact(output):
    pairs = collections.defaultdict(set)
    for line in output.splitlines():
        port, payload = line.split("\t")
        pairs[payload].add(int(port))
    lines = [f"# Nmap {VERSION} / {COMMIT}",
             "# Generated by Nmap init_payloads/get_udp_payload; ports<TAB>payload hex."]
    for payload, ports in sorted(pairs.items(), key=lambda item: (min(item[1]), item[0])):
        ranges = []
        for port in sorted(ports):
            if ranges and port == ranges[-1][1] + 1:
                ranges[-1][1] = port
            else:
                ranges.append([port, port])
        spec = ",".join(str(a) if a == b else f"{a}-{b}" for a, b in ranges)
        lines.append(f"{spec}\t{payload}")
    return "\n".join(lines) + "\n"


def main():
    source = Path(sys.argv[1]).resolve()
    # Verify the source files used by the oracle against the recorded upstream
    # hashes, so another Nmap release cannot silently bless a changed table.
    for line in (ROOT / "tests/fixtures/nmap-source.sha256").read_text().splitlines():
        digest, name = line.split()
        actual = hashlib.sha256((source / name).read_bytes()).hexdigest()
        if actual != digest:
            raise ValueError(f"wrong pinned Nmap source: {name}")
    if (source / "nmap-service-probes").read_bytes() != (ROOT / "nmap-service-probes").read_bytes():
        raise ValueError("vendored database differs from pinned Nmap source")
    with tempfile.TemporaryDirectory(prefix="rustscan-nmap-") as tmp:
        work = Path(tmp) / "nmap"
        shutil.copytree(source, work)
        main_file = work / "nmap.cc"
        text = main_file.read_text()
        marker = "int nmap_main(int argc, char *argv[]) {"
        assert text.count(marker) == 1
        main_file.write_text(text.replace(marker, marker + DUMP, 1))
        subprocess.run(["./configure", "--without-zenmap", "--without-ncat",
                        "--without-nping", "--without-ndiff", "--without-openssl",
                        "--without-liblua", "--with-libpcre=included"], cwd=work, check=True)
        subprocess.run(["make", "-j4"], cwd=work, check=True)
        output = subprocess.check_output([str(work / "nmap")], cwd=work, text=True,
                                         env={**os.environ, "NMAPDIR": str(ROOT)})
    (ROOT / "tests/fixtures/nmap-udp-selection.tsv").write_text(compact(output))


if __name__ == "__main__":
    main()
