//! Pins the probe variants generated from both Nmap databases, so a parsing
//! regression shows up as lost coverage instead of silently missed services.

#[allow(dead_code)]
#[path = "../build/nmap_payloads.rs"]
mod build_script;

use build_script::parse;
use rustscan::generated::payloads_for;

#[test]
fn service_probe_selection_matches_nmap_eligibility() {
    let entries = build_script::parse_service_probes(
        r"Exclude U:1-65535
Probe UDP First q|a#b\x7c\0\n\r\t\\|
rarity 9
ports 523,3483,5060-5061,65535
sslports 12345
Probe UDP Skip q|skip| no-payload
ports 523
Probe TCP Reset q|tcp|
ports 523
Probe UDP NoPorts q|none|
sslports 523
Probe UDP Last q@final@
ports 0,53",
    )
    .unwrap();
    assert_eq!(entries.len(), 2);
    assert_eq!(entries[0].ports, [523, 3483, 5060, 5061, 65535]);
    assert_eq!(entries[0].payload, b"a#b|\0\n\r\t\\");
    assert_eq!(entries[1].ports, [0, 53]);
    assert_eq!(entries[1].payload, b"final");
}

#[test]
fn service_probes_accept_crlf_empty_payloads_and_repeated_ports() {
    let entries = build_script::parse_service_probes(
        "Probe UDP Empty q||\r\nports 1-2, 2,65535\r\nports 3\r\n",
    )
    .unwrap();
    assert_eq!(entries[0].ports, [1, 2, 65535, 3]);
    assert!(entries[0].payload.is_empty());
}

#[test]
fn malformed_service_probes_fail_with_source_lines() {
    for record in [
        "Probe UDP Missing",
        "Probe SCTP Wrong q||",
        "Probe UDP Missing q|end",
        r"Probe UDP Bad q|\x0g|",
        r"Probe UDP Short q|\x0|",
        r"Probe UDP Unknown q|\a|",
        "Probe UDP Wrong p|body|",
    ] {
        let error = build_script::parse_service_probes(&format!("# header\n{record}")).unwrap_err();
        assert!(error.starts_with("line 2:"), "{}", error);
    }
    for ports in ["65536", "2-1", "1,bogus", ""] {
        let error =
            build_script::parse_service_probes(&format!("Probe UDP Test q||\nports {ports}"))
                .unwrap_err();
        assert!(error.starts_with("line 2:"), "{}", error);
    }
}

#[test]
fn no_payload_service_probe_is_not_added_to_legacy_variants() {
    // Sqlping is version-detection-only; there is no discovery probe on 1434.
    assert!(!payloads_for(1434).contains(&b"\x02".as_slice()));
    assert!(payloads_for(1434).is_empty());
}

#[test]
fn every_port_matches_nmaps_selection_plus_preserved_legacy_probes() {
    use std::collections::{BTreeMap, BTreeSet};
    type Probes = BTreeMap<u16, BTreeSet<Vec<u8>>>;
    fn expand(entries: Vec<build_script::Entry>) -> Probes {
        let mut result = Probes::new();
        for entry in entries {
            for port in entry.ports {
                result
                    .entry(port)
                    .or_default()
                    .insert(entry.payload.clone());
            }
        }
        result
    }

    // This fixture is exported by the pinned Nmap executable's payload API,
    // not generated by our parser. See tests/nmap_reference.py to regenerate.
    let mut nmap = Probes::new();
    for line in include_str!("fixtures/nmap-udp-selection.tsv").lines() {
        if line.starts_with('#') {
            continue;
        }
        let (ports, hex) = line.split_once('\t').unwrap();
        let payload: Vec<u8> = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
            .collect();
        for spec in ports.split(',') {
            let (first, last) = spec.split_once('-').unwrap_or((spec, spec));
            for port in first.parse::<u16>().unwrap()..=last.parse().unwrap() {
                nmap.entry(port).or_default().insert(payload.clone());
            }
        }
    }
    assert_eq!(nmap.len(), 33_110);
    assert_eq!(nmap.values().map(BTreeSet::len).sum::<usize>(), 33_204);
    let services =
        expand(build_script::parse_service_probes(include_str!("../nmap-service-probes")).unwrap());
    let legacy = expand(parse(include_str!("../nmap-payloads")).unwrap());
    let empty = BTreeSet::new();
    for port in 0..=u16::MAX {
        let reference = nmap.get(&port).unwrap_or(&empty);
        assert_eq!(
            services.get(&port).unwrap_or(&empty),
            reference,
            "Nmap selection udp/{port}"
        );
        let expected: BTreeSet<_> = reference
            .union(legacy.get(&port).unwrap_or(&empty))
            .map(Vec::as_slice)
            .collect();
        let generated: BTreeSet<_> = payloads_for(port).iter().copied().collect();
        assert_eq!(generated, expected, "merged selection udp/{port}");
    }
}

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    haystack.windows(needle.len()).any(|w| w == needle)
}

#[test]
fn comments_do_not_remove_payloads_or_literal_hashes() {
    let entries = parse(
        r##"
# comment with "unbalanced quotes
udp 623 # header comment
"a#b" # trailing comment
"\"#\\" # escaped quote and backslash before the closing quote
"\x80\0"
"##,
    )
    .unwrap();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].payload, b"a#b\"#\\\x80\0");
}

#[test]
fn ranges_include_both_endpoints_and_deduplicate_ports() {
    let entries = parse("udp 1198-1199,1199,65534-65535,8-8 \"probe\"").unwrap();
    assert_eq!(entries[0].ports, [8, 1198, 1199, 65534, 65535]);
}

#[test]
fn duplicate_and_overlapping_port_lists_preserve_every_entry() {
    let entries =
        parse("udp 53,123 \"first\"\nudp 53,123 \"second\"\nudp 123-124 \"third\"").unwrap();
    assert_eq!(entries.len(), 3);
    assert_eq!(entries[0].payload, b"first");
    assert_eq!(entries[1].payload, b"second");
    assert_eq!(entries[2].ports, [123, 124]);
    assert_eq!(entries[2].payload, b"third");
}

#[test]
fn flushes_single_and_final_entries_without_a_trailing_newline() {
    for input in ["udp 48899 \"ads\"", "udp 53 \"dns\"\nudp 48899 \"ads\""] {
        let entries = parse(input).unwrap();
        assert_eq!(entries.last().unwrap().ports, [48899]);
        assert_eq!(entries.last().unwrap().payload, b"ads");
    }
}

#[test]
fn accepts_indented_headers_tabs_and_multiline_entries() {
    let entries = parse("  udp\t53\n\"a\"\n\"b\"\n\tudp\n123\n\"c\"").unwrap();
    assert_eq!(entries[0].ports, [53]);
    assert_eq!(entries[0].payload, b"ab");
    assert_eq!(entries[1].ports, [123]);
    assert_eq!(entries[1].payload, b"c");
}

#[test]
fn invalid_entries_fail_with_the_source_line_instead_of_losing_coverage() {
    for entry in ["udp 2-1 \"x\"", "udp 65536 \"x\"", "udp 53", "tcp 53 \"x\""] {
        let error = parse(&format!("# comment\n{entry}")).unwrap_err();
        assert!(error.starts_with("line 2:"), "{}", error);
    }
}

#[test]
fn generated_lookup_matches_every_vendored_entry_and_gap() {
    use std::collections::BTreeMap;
    let mut entries = parse(include_str!("../nmap-payloads")).unwrap();
    entries.extend(
        build_script::parse_service_probes(include_str!("../nmap-service-probes")).unwrap(),
    );
    let mut expected: BTreeMap<u16, Vec<Vec<u8>>> = BTreeMap::new();
    for entry in entries {
        for port in entry.ports {
            let variants = expected.entry(port).or_default();
            if !variants.contains(&entry.payload) {
                variants.push(entry.payload.clone());
            }
        }
    }
    for port in 0..=u16::MAX {
        let variants: Vec<&[u8]> = expected
            .get(&port)
            .into_iter()
            .flatten()
            .map(Vec::as_slice)
            .collect();
        assert_eq!(payloads_for(port), variants, "udp/{port}");
    }
}

#[test]
fn rmcp_asf_and_ipmi_both_survive_trailing_comments_and_shared_ports() {
    let payloads = payloads_for(623);
    assert!(payloads.contains(&b"\x06\0\xff\x06\0\0\x11\xbe\x80\0\0\0".as_slice()));
    assert!(payloads.iter().any(|p| p.starts_with(b"\x06\0\xff\x07")));
    assert_eq!(payloads.len(), 2);
}

#[test]
fn final_ads_entry_survives_alongside_the_overlapping_rpc_probe() {
    let payloads = payloads_for(48899);
    assert!(payloads.contains(
        &b"\x03\x66\x14\x71\0\0\0\0\x01\0\0\0\0\0\0\0\x01\x01\x10\x27\0\0\0\0".as_slice()
    ));
    assert!(payloads.iter().any(|p| p.len() == 40));
    assert_eq!(payloads.len(), 2);
}

#[test]
fn range_endpoints_have_the_same_probes_as_the_previous_port() {
    for end in [1199, 26004, 27030, 27914, 27964, 30724, 65535] {
        let payloads = payloads_for(end);
        assert!(!payloads.is_empty(), "missing udp/{}", end);
        assert_eq!(payloads, payloads_for(end - 1), "udp/{end}");
    }
}

#[test]
fn overlapping_dns_and_shared_snmp_keys_preserve_variants() {
    let dns = payloads_for(53);
    assert!(dns.contains(&b"\0\0\x10\0\0\0\0\0\0\0\0\0".as_slice()));
    assert!(dns.iter().any(|p| contains(p, b"version")));
    assert_eq!(dns.len(), 4);
    let snmp = payloads_for(161);
    assert!(snmp.iter().any(|p| p.starts_with(b"\x30\x3a\x02\x01\x03")));
    assert_eq!(snmp.len(), 3);
}

#[test]
fn generated_variants_are_unique_and_shared_across_ports() {
    for port in 0..=u16::MAX {
        let payloads = payloads_for(port);
        for (index, payload) in payloads.iter().enumerate() {
            assert!(!payloads[..index].contains(payload));
        }
    }
    let first = payloads_for(2049)[0];
    let last = payloads_for(65535)[0];
    assert!(
        std::ptr::eq(first, last),
        "RPC payload bytes must be shared across separate port ranges"
    );
}

#[test]
fn vendored_database_coverage_and_packet_budget_are_preserved() {
    let counts: Vec<_> = (1..=u16::MAX)
        .map(|port| payloads_for(port).len())
        .collect();
    let actual = (
        counts.iter().filter(|&&count| count > 0).count(),
        counts.iter().sum::<usize>(),
        counts.iter().filter(|&&count| count > 1).count(),
        counts.iter().max().copied(),
    );
    assert_eq!(
        actual,
        (33_111, 33_251, 124, Some(5)),
        "probe coverage changed: investigate lost probes or update after syncing the Nmap databases"
    );
}

#[test]
fn full_range_datagram_budget_includes_empty_fallbacks() {
    let per_attempt: usize = (1..=u16::MAX)
        .map(|port| payloads_for(port).len().max(1))
        .sum();
    assert_eq!(per_attempt, 65_675);
    assert_eq!(per_attempt * 2, 131_350);
    assert!(payloads_for(0).is_empty());
}
